require('dotenv').config();
const express=require('express');const helmet=require('helmet');const cors=require('cors');const path=require('path');const fs=require('fs');const crypto=require('crypto');const Database=require('better-sqlite3');
const app=express();const port=Number(process.env.PORT||3000);const db=new Database(path.join(__dirname,'..','database','kemosat.db'));db.pragma('foreign_keys=ON');db.exec(fs.readFileSync(path.join(__dirname,'..','database','schema.sql'),'utf8'));
app.use(helmet({contentSecurityPolicy:false}));app.use(cors({origin:true,credentials:true}));app.use(express.json({limit:'200kb'}));app.use(express.static(path.join(__dirname,'..','public')));
const hashToken=t=>crypto.createHash('sha256').update(t).digest('hex');
function verifyPassword(password,stored){const [hex,salt]=stored.split(':');const a=Buffer.from(hex,'hex');const b=crypto.scryptSync(password,salt,64);return a.length===b.length&&crypto.timingSafeEqual(a,b)}
function admin(req,res,next){const raw=(req.headers.authorization||'').replace(/^Bearer\s+/,'');if(!raw)return res.status(401).json({error:'غير مصرح'});const s=db.prepare('SELECT admin_id,expires_at FROM sessions WHERE token_hash=?').get(hashToken(raw));if(!s||new Date(s.expires_at)<new Date())return res.status(401).json({error:'انتهت الجلسة'});req.adminId=s.admin_id;next()}
function shipping(g){return g==='القاهرة'?60:g==='الجيزة'?65:100}
app.get('/api/health',(req,res)=>res.json({ok:true,service:'KemoSat Egypt',time:new Date().toISOString()}));
app.get('/api/config',(req,res)=>res.json({instapay:!!process.env.INSTAPAY_HANDLE,wallet:!!process.env.WALLET_NUMBER,provider:process.env.PAYMENT_PROVIDER||null}));
app.get('/api/products',(req,res)=>res.json(db.prepare('SELECT * FROM products WHERE active=1 ORDER BY id DESC').all()));
app.post('/api/admin/login',(req,res)=>{const {email,password}=req.body||{};const a=db.prepare('SELECT * FROM admins WHERE email=?').get(email);if(!a||!verifyPassword(password||'',a.password_hash))return res.status(401).json({error:'بيانات الدخول غير صحيحة'});const token=crypto.randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions(token_hash,admin_id,expires_at) VALUES(?,?,?)').run(hashToken(token),a.id,new Date(Date.now()+1000*60*60*12).toISOString());res.json({token,email:a.email})});
app.post('/api/admin/logout',admin,(req,res)=>{const raw=(req.headers.authorization||'').replace(/^Bearer\s+/,'');db.prepare('DELETE FROM sessions WHERE token_hash=?').run(hashToken(raw));res.json({ok:true})});
app.get('/api/admin/stats',admin,(req,res)=>{const products=db.prepare('SELECT COUNT(*) c FROM products WHERE active=1').get().c;const orders=db.prepare('SELECT COUNT(*) c FROM orders').get().c;const customers=db.prepare('SELECT COUNT(*) c FROM customers').get().c;const sales=db.prepare("SELECT COALESCE(SUM(total_egp),0) s FROM orders WHERE payment_status='paid' OR payment_method='cod'").get().s;res.json({products,orders,customers,sales})});
app.get('/api/admin/orders',admin,(req,res)=>res.json(db.prepare(`SELECT o.*,c.name,c.phone,c.governorate,c.address FROM orders o JOIN customers c ON c.id=o.customer_id ORDER BY o.id DESC`).all()));
app.patch('/api/admin/orders/:id',admin,(req,res)=>{const allowed=['new','processing','shipped','completed','cancelled'];const {status,paymentStatus}=req.body||{};if(status&&!allowed.includes(status))return res.status(400).json({error:'حالة غير صالحة'});if(status)db.prepare('UPDATE orders SET status=? WHERE id=?').run(status,req.params.id);if(paymentStatus)db.prepare('UPDATE orders SET payment_status=? WHERE id=?').run(paymentStatus,req.params.id);res.json({ok:true})});
app.post('/api/admin/products',admin,(req,res)=>{const {name_ar,category,price_egp,old_price_egp,stock,image_url}=req.body||{};if(!name_ar||!category||!Number.isFinite(Number(price_egp)))return res.status(400).json({error:'بيانات المنتج غير مكتملة'});const r=db.prepare('INSERT INTO products(name_ar,category,price_egp,old_price_egp,stock,image_url) VALUES(?,?,?,?,?,?)').run(name_ar,category,Number(price_egp),Number(old_price_egp)||null,Number(stock)||0,image_url||null);res.status(201).json({id:r.lastInsertRowid})});
app.patch('/api/admin/products/:id',admin,(req,res)=>{const p=req.body||{};db.prepare('UPDATE products SET name_ar=COALESCE(?,name_ar),category=COALESCE(?,category),price_egp=COALESCE(?,price_egp),old_price_egp=COALESCE(?,old_price_egp),stock=COALESCE(?,stock),image_url=COALESCE(?,image_url),active=COALESCE(?,active) WHERE id=?').run(p.name_ar,p.category,p.price_egp,p.old_price_egp,p.stock,p.image_url,p.active,req.params.id);res.json({ok:true})});
app.post('/api/payments/paymob/intention', async (req,res)=>{
  if(!process.env.PAYMOB_SECRET_KEY||!process.env.PAYMOB_PUBLIC_KEY||!process.env.PAYMOB_INTEGRATION_ID) return res.status(503).json({error:'بوابة Paymob غير مهيأة بعد'});
  const {orderCode}=req.body||{}; const order=db.prepare('SELECT o.*,c.name,c.phone,c.email,c.address,c.governorate FROM orders o JOIN customers c ON c.id=o.customer_id WHERE o.order_code=?').get(orderCode);
  if(!order)return res.status(404).json({error:'الطلب غير موجود'});
  const items=db.prepare('SELECT * FROM order_items WHERE order_id=?').all(order.id);
  const parts=(order.name||'KemoSat Customer').trim().split(/\s+/);const first=parts.shift()||'Customer',last=parts.join(' ')||'KemoSat';
  const body={amount:order.total_egp*100,currency:'EGP',payment_methods:String(process.env.PAYMOB_INTEGRATION_ID).split(',').map(Number),items:[...items.map(x=>({name:x.product_name.slice(0,50),amount:x.unit_price_egp*100,description:x.product_name.slice(0,255),quantity:x.quantity})),...(order.shipping_fee_egp?[{name:'الشحن',amount:order.shipping_fee_egp*100,description:'رسوم الشحن',quantity:1}]:[])],billing_data:{apartment:'NA',first_name:first,last_name:last,street:order.address.slice(0,100),building:'NA',phone_number:order.phone,city:order.governorate,country:'EGY',email:order.email,floor:'NA',state:order.governorate},special_reference:order.order_code,notification_url:`${process.env.APP_URL}/api/payments/paymob/webhook`,redirection_url:`${process.env.APP_URL}/payment-success.html`};
  try{const r=await fetch('https://accept.paymob.com/v1/intention/',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Token '+process.env.PAYMOB_SECRET_KEY},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)return res.status(502).json({error:'فشل إنشاء عملية الدفع',details:d});db.prepare('UPDATE orders SET payment_reference=? WHERE id=?').run(d.id||d.intention_order_id,order.id);res.json({checkoutUrl:`https://accept.paymob.com/unifiedcheckout/?publicKey=${encodeURIComponent(process.env.PAYMOB_PUBLIC_KEY)}&clientSecret=${encodeURIComponent(d.client_secret)}`});}catch(e){res.status(502).json({error:'تعذر الاتصال ببوابة الدفع'})}
});
app.post('/api/payments/paymob/webhook',(req,res)=>{
  const obj=req.body?.obj; const received=String(req.query.hmac||''); const secret=process.env.PAYMOB_HMAC_SECRET;
  if(!secret||!obj||!received)return res.status(401).json({error:'Invalid HMAC'});
  const fields=[obj.amount_cents,obj.created_at,obj.currency,obj.error_occured,obj.has_parent_transaction,obj.id,obj.integration_id,obj.is_3d_secure,obj.is_auth,obj.is_capture,obj.is_refunded,obj.is_standalone_payment,obj.is_voided,obj.order?.id,obj.owner,obj.pending,obj.source_data?.pan,obj.source_data?.sub_type,obj.source_data?.type,obj.success];
  const digest=crypto.createHmac('sha512',secret).update(fields.map(v=>String(v??'')).join('')).digest('hex');
  const a=Buffer.from(digest,'hex'),b=Buffer.from(received,'hex');if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return res.status(401).json({error:'Invalid HMAC'});
  const ref=obj.order?.merchant_order_id; if(ref){const status=obj.success===true&&obj.pending===false?'paid':'failed';db.prepare('UPDATE orders SET payment_status=? WHERE order_code=?').run(status,ref)}res.json({received:true});
});
app.post('/api/orders', (req,res)=>{const {name,phone,email,governorate,address,paymentMethod,items}=req.body||{};if(!name||!phone||!email||!governorate||!address||!paymentMethod||!Array.isArray(items)||!items.length)return res.status(400).json({error:'بيانات الطلب غير مكتملة'});const clean=items.map(x=>({id:Number(x.id),quantity:Number(x.quantity)})).filter(x=>x.id>0&&x.quantity>0&&x.quantity<=99);if(!clean.length)return res.status(400).json({error:'المنتجات غير صالحة'});const get=db.prepare('SELECT id,name_ar,price_egp,stock FROM products WHERE id=? AND active=1');let subtotal=0,details=[];for(const item of clean){const p=get.get(item.id);if(!p)return res.status(400).json({error:'منتج غير موجود'});if(p.stock<item.quantity)return res.status(409).json({error:`المخزون غير كافٍ: ${p.name_ar}`});subtotal+=p.price_egp*item.quantity;details.push({...item,p})}const fee=shipping(governorate),total=subtotal+fee,code='KS-'+Date.now().toString(36).toUpperCase();const tx=db.transaction(()=>{let c=db.prepare('SELECT id FROM customers WHERE phone=?').get(phone);if(c)db.prepare('UPDATE customers SET name=?,email=?,governorate=?,address=? WHERE id=?').run(name,email||null,governorate,address,c.id);else{const r=db.prepare('INSERT INTO customers(name,phone,email,governorate,address) VALUES(?,?,?,?,?)').run(name,phone,email||null,governorate,address);c={id:r.lastInsertRowid}}const status=paymentMethod==='cod'?'pending':'awaiting';const o=db.prepare('INSERT INTO orders(order_code,customer_id,total_egp,payment_method,payment_status,shipping_fee_egp) VALUES(?,?,?,?,?,?)').run(code,c.id,total,paymentMethod,status,fee);const oi=db.prepare('INSERT INTO order_items(order_id,product_id,product_name,unit_price_egp,quantity) VALUES(?,?,?,?,?)');const up=db.prepare('UPDATE products SET stock=stock-? WHERE id=?');details.forEach(x=>{oi.run(o.lastInsertRowid,x.p.id,x.p.name_ar,x.p.price_egp,x.quantity);up.run(x.quantity,x.p.id)})});tx();res.status(201).json({orderCode:code,subtotalEgp:subtotal,shippingEgp:fee,totalEgp:total,paymentStatus:paymentMethod==='cod'?'pending':'awaiting'});});
app.use((req,res)=>res.sendFile(path.join(__dirname,'..','public','index.html')));app.listen(port,()=>console.log(`KemoSat running on http://localhost:${port}`));
